{{- if .Values.googleAdminCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-google-admin-credentials
  namespace: {{ template "grafana-rbac-controller.namespace" . }}
data:
  credentials.json: {{ .Values.googleAdminCredentials.credentials | b64enc | quote }}
type: Opaque
{{- end }}