{{- if .Values.grafanaAdminCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-admin-credentials
  namespace: {{ template "grafana-rbac-controller.namespace" . }}
data:
  grafana-admin-password: {{ .Values.grafanaAdminCredentials.password | b64enc | quote }}
type: Opaque
{{- end }}