{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "grafana-rbac-controller.fullname" . }}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressClassName := .Values.ingress.className -}}
{{- $ingressPathType := .Values.ingress.pathType -}}
apiVersion: {{ include "common.capabilities.networkPolicy.apiVersion" . }}
kind: Ingress
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4}}
{{- end }}
  labels:
{{ template "grafana-rbac-controller.defaultLabels" merge (dict "extraLabels" dict) .  }}
  name: {{ template "grafana-rbac-controller.fullname" . }}
  namespace: {{ template "grafana-rbac-controller.namespace" . }}
spec:
  {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
  ingressClassName: {{ $ingressClassName }}
  {{- end }}
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $ingressPath }}
            {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
    {{- end -}}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
