{{- if .Values.oauth2Proxy.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oauth2-proxy-credentials
  namespace: {{ template "grafana-rbac-controller.namespace" . }}
type: Opaque
data:
  oauth2-proxy-client-id: {{ .Values.oauth2Proxy.credentials.clientID | b64enc | quote }}
  oauth2-proxy-client-secret: {{ .Values.oauth2Proxy.credentials.secret | b64enc | quote }}
  oauth2-proxy-cookie-secret : {{ .Values.oauth2Proxy.credentials.cookie | b64enc | quote }}
{{ end }}
