apiVersion: v1
kind: Service
metadata:
  name: {{ template "grafana-rbac-controller.fullname" . }}
  namespace: {{ template "grafana-rbac-controller.namespace" . }}
  annotations:
{{ .Values.serviceAnnotations | toYaml | indent 4 }}
  labels:
{{ template "grafana-rbac-controller.defaultLabels" merge (dict "extraLabels" .Values.serviceLabels) .  }}
spec:
{{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "grafana-rbac-controller.name" . }}
    release: {{ .Release.Name }}
