name: Releases
on:
  push:
    branches:
      - main


env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  
  
jobs:
  changelog:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Create release tag
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          github-token: ${{ secrets.RELEASE_TOKEN }}
          
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
        if: ${{ steps.release.outputs.release_created }}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        if: ${{ steps.release.outputs.release_created }}
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.RELEASE_TOKEN }}

      - id: container_registry
        uses: ASzc/change-string-case-action@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          string: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        if: ${{ steps.release.outputs.release_created }}
        with:
          context: .
          push: true
          tags: |
            ${{ steps.container_registry.outputs.lowercase }}:${{ steps.release.outputs.tag_name }}
            ${{ steps.container_registry.outputs.lowercase }}:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
